co2_price: 130 # €/t

get_results: True #if True the the scenario generation is not run and the results is downloaded from https://zenodo.org/records/13619460

countries:
 - DE:
   - bus: 20
 - GB:
   - bus: 14
 - ES:
   - bus: 8

transmission_limit:
 - 1.0
 - 1.5

contingencies: 
 - pv:
   - reductionto: [0,0.25,0.5,0.75]
   - duration: [90,180,270]
 - wind:
   - reductionto: [0,0.25,0.5,0.75]
   - duration: [90,180,270]
 - noexim:
   - reductionto: [0,0.25,0.5,0.75]
   - duration: [90,180,270]
 - drought:
   - reductionto: [0,0.25,0.5,0.75]
   - duration: [90,180,270]
 - windpv:
   - reductionto: [0,0.25,0.5,0.75]
   - duration: [7,14,21]

#cut_start: '2013-02-01 00:00:00'

models:
 - inv
 - noinv

horizon: 24 #3 days of horizon for models with 3h temporal resolution


min_equity: 'EQ0.95c'




